name: Backup Firestore

on:
  schedule:
    - cron:  //YOUR-INTERVAL//

env:
  PROJECT_ID: YOUR-PROJECT
  BUCKET: gs://YOUR-BUCKET
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET
